#############################################################################
# Makefile for building: ATK3
# Generated by qmake (2.01a) (Qt 4.7.3) on: Sat Jan 7 23:24:50 2012
# Project:  ATK3.pro
# Template: app
# Command: /usr/local/bin/qmake4 -o Makefile ATK3.pro
#############################################################################

LOCALBASE= /usr/local
X11BASE  = /usr/X11R6

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -fno-wrapv $(COPTS) -O2 -fno-wrapv $(COPTS) -Wall -W -pthread $(DEFINES)
CXXFLAGS      = -pipe -O2 -fno-wrapv $(COPTS) -O2 -fno-wrapv $(COPTS) -Wall -W -pthread $(DEFINES)
INCPATH       = -I/usr/local/lib/qt4/mkspecs/openbsd-g++4 -I. -I/usr/local/include/X11/qt4/QtCore -I/usr/local/include/X11/qt4/QtNetwork -I/usr/local/include/X11/qt4/QtGui -I/usr/local/include/X11/qt4 -I. -I$(LOCALBASE)/include
LINK          = g++
LFLAGS        = -pthread
LIBS          = $(SUBLIBS)  -L$(LOCALBASE)/lib -L/usr/local/lib/qt4 -lQtGui -L/usr/local/lib/qt4 -L/usr/X11R6/lib -L/usr/local/lib/mysql -L$(LOCALBASE)/lib -L$(X11BASE)/lib -lQtNetwork -lQtCore 
AR            = ar q
RANLIB        = ranlib
QMAKE         = /usr/local/bin/qmake4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = StickListener.cpp \
		main.cpp moc_StickListener.cpp
OBJECTS       = StickListener.o \
		main.o \
		moc_StickListener.o
DIST          = /usr/local/lib/qt4/mkspecs/common/unix.conf \
		/usr/local/lib/qt4/mkspecs/qconfig.pri \
		/usr/local/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt4/mkspecs/features/release.prf \
		/usr/local/lib/qt4/mkspecs/features/default_post.prf \
		/usr/local/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt4/mkspecs/features/qt.prf \
		/usr/local/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt4/mkspecs/features/moc.prf \
		/usr/local/lib/qt4/mkspecs/features/resources.prf \
		/usr/local/lib/qt4/mkspecs/features/uic.prf \
		/usr/local/lib/qt4/mkspecs/features/yacc.prf \
		/usr/local/lib/qt4/mkspecs/features/lex.prf \
		/usr/local/lib/qt4/mkspecs/features/include_source_dir.prf \
		ATK3.pro
QMAKE_TARGET  = ATK3
DESTDIR       = 
TARGET        = ATK3

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ATK3.pro  /usr/local/lib/qt4/mkspecs/openbsd-g++4/qmake.conf /usr/local/lib/qt4/mkspecs/common/unix.conf \
		/usr/local/lib/qt4/mkspecs/qconfig.pri \
		/usr/local/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt4/mkspecs/features/release.prf \
		/usr/local/lib/qt4/mkspecs/features/default_post.prf \
		/usr/local/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt4/mkspecs/features/qt.prf \
		/usr/local/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt4/mkspecs/features/moc.prf \
		/usr/local/lib/qt4/mkspecs/features/resources.prf \
		/usr/local/lib/qt4/mkspecs/features/uic.prf \
		/usr/local/lib/qt4/mkspecs/features/yacc.prf \
		/usr/local/lib/qt4/mkspecs/features/lex.prf \
		/usr/local/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/local/lib/qt4/libQtGui.prl \
		/usr/local/lib/qt4/libQtCore.prl \
		/usr/local/lib/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile ATK3.pro
/usr/local/lib/qt4/mkspecs/common/unix.conf:
/usr/local/lib/qt4/mkspecs/qconfig.pri:
/usr/local/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt4/mkspecs/features/qt_config.prf:
/usr/local/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt4/mkspecs/features/default_pre.prf:
/usr/local/lib/qt4/mkspecs/features/release.prf:
/usr/local/lib/qt4/mkspecs/features/default_post.prf:
/usr/local/lib/qt4/mkspecs/features/warn_on.prf:
/usr/local/lib/qt4/mkspecs/features/qt.prf:
/usr/local/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt4/mkspecs/features/moc.prf:
/usr/local/lib/qt4/mkspecs/features/resources.prf:
/usr/local/lib/qt4/mkspecs/features/uic.prf:
/usr/local/lib/qt4/mkspecs/features/yacc.prf:
/usr/local/lib/qt4/mkspecs/features/lex.prf:
/usr/local/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/local/lib/qt4/libQtGui.prl:
/usr/local/lib/qt4/libQtCore.prl:
/usr/local/lib/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ATK3.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ATK31.0.0 || $(MKDIR) .tmp/ATK31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ATK31.0.0/ && $(COPY_FILE) --parents StickListener.h .tmp/ATK31.0.0/ && $(COPY_FILE) --parents StickListener.cpp main.cpp .tmp/ATK31.0.0/ && (cd `dirname .tmp/ATK31.0.0` && $(TAR) ATK31.0.0.tar ATK31.0.0 && $(COMPRESS) ATK31.0.0.tar) && $(MOVE) `dirname .tmp/ATK31.0.0`/ATK31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ATK31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_StickListener.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_StickListener.cpp
moc_StickListener.cpp: StickListener.h
	/usr/local/lib/qt4/bin/moc $(DEFINES) $(INCPATH) StickListener.h -o moc_StickListener.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

StickListener.o: StickListener.cpp StickListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StickListener.o StickListener.cpp

main.o: main.cpp StickListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_StickListener.o: moc_StickListener.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StickListener.o moc_StickListener.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

